name: Backdate Commits 2024

on:
  workflow_dispatch:

jobs:
  backdate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Backdated Commits for 2024
        run: |
          git config user.name "HBR0105"
          git config user.email "hbrajapakshaedu@gmail.com"
          
          mkdir -p backdated_commits

          # Define month-based commit targets
          declare -A month_commit_count=( [1]=10 [2]=10 [3]=5 [4]=10 )
          
          for month in 1 2 3 4; do
            count=${month_commit_count[$month]}
            for i in $(seq 1 $count); do
              day=$((RANDOM % 28 + 1))
              date_str="2024-$(printf "%02d" $month)-$(printf "%02d" $day) 12:00:00"
              file_path="backdated_commits/2024_${month}_${day}_commit_$i.txt"
              echo "Backdated commit #$i on $date_str - $(uuidgen)" > "$file_path"
              git add "$file_path"
              GIT_COMMITTER_DATE="$date_str" git commit --date="$date_str" -m "Backdated commit #$i on $date_str"
            done
          done
          
          git push || echo "No changes to push"
