      - name: Generate Backdated Commits with Random Content
        run: |
          git config user.name "HBR0105"
          git config user.email "hbrajapakshaedu@gmail.com"
          
          mkdir -p backdated_commits
          
          year=2024
          for month in {1..12}; do
            for day in {1..28}; do
              count=$(( RANDOM % 5 + 1 ))
              for i in $(seq 1 $count); do
                date_str="$year-$(printf "%02d" $month)-$(printf "%02d" $day) 12:00:00"
                file_path="backdated_commits/${year}_${month}_${day}_commit_$i.txt"
                if [ ! -f "$file_path" ]; then
                  echo "Backdated commit #$i on $date_str - $(uuidgen)" > "$file_path"
                  git add "$file_path"
                  GIT_COMMITTER_DATE="$date_str" git commit --date="$date_str" -m "Backdated commit #$i on $date_str"
                fi
              done
            done
          done
          
          git push || echo "No changes to push"
